<?php echo $this->doctype(); ?>

<html lang="pt-BR">
<head>
	<meta charset="utf-8">
	<!--start Facebook Open Graph Protocol-->
	  <!-- Title Head -->
        <?php
        $NAME_APPLICATION = 'Limpeza Fácil';
        echo $this->headTitle($NAME_APPLICATION)
                ->setSeparator(' - ')
                ->setAutoEscape(false)
        ;
        ?>
 		<meta name="description" content="Quer ter mais tempo livre para fazer o que gosta?">
		<meta name="keywords" content="gurupi, compras online, limpeza facil,produtos de limpeza">
		<!-- Meta Head -->
        <?php
        echo $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ;
        ?>
 		 <!-- Styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favico.ico'))
        		->prependStylesheet($this->basePath() . '/css/extra.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
        ;
        ?>
	
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-41616325-5', 'limpezafacil.com');
		  ga('send', 'pageview');
	
		</script>
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/masked-input.js')
                ->prependFile($this->basePath() . '/js/facebook.js')
		        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		        ->prependFile($this->basePath() . '/js/scripts.js')
		        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
		        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ;
 
        echo $this->inlineScript();
        ?>
	
	
</head>

<body>

	<div class="container">
		<div class="row clearfix">
			<div class="col-md-4 col-md-offset-4">

				<a href="http://limpezafacil.com"><img class="img-responsive" width="100%" alt="Limpeza Fácil"
					src="/img/logo3.png"></a>
				<div class="vert-text">
					<h1>
						+ tempo <em>Livre</em>
					</h1>
					<h4>
						+ tempo pra você <em>fazer</em> o que <em>gosta</em>
					</h4>
				</div>
			</div>
		</div>
		<hr>
		
		<?php echo $this->content; ?>
		
		<hr>
		<div class="row clearfix">
			<div class="col-md-12 column">
				<h3 class="text-center">LimpezaFacil 2014 - Gurupi</h3>
			</div>
		</div>
	</div>
</body>
</html>
