<div class="container">
	<div class="row">
		<div class="col-md-12 column">
			<div class="panel panel-default">

				<div class="panel-heading">
					<center>
						<h2>
							Obrigado
							<?php echo $this->nome; ?>
						</h2>
					</center>
				</div>
				<div class="panel-body">
					<center>
						<h2>Entraremos em contato com Você.</h2>
						<h3>Compartilhe essa Ideia:</h3>

						<div id="fb-root"></div>
						<div class="fb-share-button" data-href="http://limpezafacil.com"
							data-width="450" data-type="box_count"></div>
					</center>

					<br>
				</div>
				<div class="panel-footer"></div>
			</div>
		</div>
	</div>
</div>
