<div class="row clearfix ">
	<div class="col-md-6 column">
		<div class="video-container">
			<iframe
				src="//player.vimeo.com/video/90059051?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff"
				width="500" height="281" frameborder="0" webkitallowfullscreen
				mozallowfullscreen allowfullscreen> </iframe>
		</div>
	</div>
	<div class="col-md-6 column">
		<div class="col-md-12 column">
			<?php
			$form = $this->form;
			$form->setAttribute('action',
			$this->url('application',
							array(	'controller' => 'Application\Controller\Index',
							'action'=>'add'
							)));
			$form->setAttribute('class', 'form-horizontal');
			$form->prepare();
			
			echo $this->form()->openTag($form);
			
			echo $this->formHidden($form->get('id')); ?>

			<div class="form-group">
				<?php echo $this->formRow($form->get('nome')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('email')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('telefone')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formRow($form->get('setor')); ?>
				<p class="help-block">Se não souber o setor pode digitar o
					endereço.</p>
			</div>
			<?php echo $this->formSubmit($form->get('submit')); ?>
			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>

</div>

<div id="fb-root"></div>
